CREATE DATABASE Autos;
USE Autos;

CREATE TABLE Autos (
id INT NOT NULL,
modelo VARCHAR2(15) NOT NULL,
anio VARCHAR2(15) NOT NULL DEFAULT 2016,
foto VARCHAR2(15) NOT NULL DEFAULT 'auto1.jpg',
papeles INT NOT NULL DEFAULT 0,
puertas INT NOT NULL DEFAULT 4,
llantas INT NOT NULL DEFAULT 4
CONSTRAINT PK_AUTO_ID
PRIMARY KEY (id));

