/***  Objetivo:  El objetivo de este jFrame es el de almacenar la interfaz grafica para hacer las
 * funciones de agregar,modificar y eliminar del CRUD.
 ***@version    V1.0 2/11/2016
 *@author    Ariel Troncoso/Enzo Troncoso
 */
package view;
import model.Auto;
import auto.Datos;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
/**
 *
 * @author AriieelEsteban
 */
public class Registro extends javax.swing.JFrame {

    private int tipo = -1;
    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        
    }
    
    public void error( String text ) {
        JOptionPane.showMessageDialog(null,
                 text,
                 "Revisar los Datos", JOptionPane.ERROR_MESSAGE);
    }
    public void valido( String text ) {
        JOptionPane.showMessageDialog(null,
                 text,
                 "Mensaje", JOptionPane.PLAIN_MESSAGE);
    }
    
    public static boolean isNumeric(String str)  
    {  
        try { double d = Double.parseDouble(str); }  
        catch(NumberFormatException nfe) { return false; }
        return true;  
    }

    
    private void limpiar( boolean valor, int i ){
        if ( valor ) {
            jTextFieldModelo.setText("");
            jTextFieldAnio.setText("");
            jTextFieldID.setText("");
            jTextFieldFoto.setText("");
            buttonGroupPapeles.clearSelection();
            buttonGroupSeguro.clearSelection();
            
            jComboBoxLlantas.setSelectedIndex(0);
            jComboBoxLujo.setSelectedIndex(0);
            jComboBoxPuertas.setSelectedIndex(0);
        }
        switch(i){
            case 0: { jTextFieldID.requestFocus(); } break;
            case 1: { jTextFieldModelo.requestFocus(); } break;
            case 2: { jTextFieldAnio.requestFocus(); } break;
            case 3: { jTextFieldFoto.requestFocus(); } break;
            default: {
                jTextFieldID.requestFocus();
            }
            break;
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupPapeles = new javax.swing.ButtonGroup();
        buttonGroupSeguro = new javax.swing.ButtonGroup();
        jLabelModelo = new javax.swing.JLabel();
        jLabelAnio = new javax.swing.JLabel();
        jLabelPuertas = new javax.swing.JLabel();
        jTextFieldModelo = new javax.swing.JTextField();
        jTextFieldAnio = new javax.swing.JTextField();
        jComboBoxPuertas = new javax.swing.JComboBox<>();
        jLabelPapeles = new javax.swing.JLabel();
        jRadioButtonPapelesSi = new javax.swing.JRadioButton();
        jRadioButtonPapelesNo = new javax.swing.JRadioButton();
        jButtonAgregar = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jLabelID = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jButtonVolver = new javax.swing.JButton();
        jLabelLlantas = new javax.swing.JLabel();
        jComboBoxLlantas = new javax.swing.JComboBox<>();
        jButtonBuscar = new javax.swing.JButton();
        jLabelFoto = new javax.swing.JLabel();
        jTextFieldFoto = new javax.swing.JTextField();
        jLabelFotoStr = new javax.swing.JLabel();
        jLabelSeguro = new javax.swing.JLabel();
        jRadioButtonSeguroSi = new javax.swing.JRadioButton();
        jRadioButtonSeguroNo = new javax.swing.JRadioButton();
        jLabelLujo = new javax.swing.JLabel();
        jComboBoxLujo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro");

        jLabelModelo.setText("Modelo:");

        jLabelAnio.setText("Año:");

        jLabelPuertas.setText("Puertas:");

        jComboBoxPuertas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        jComboBoxPuertas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPuertasActionPerformed(evt);
            }
        });

        jLabelPapeles.setText("Papeles al dia?");

        buttonGroupPapeles.add(jRadioButtonPapelesSi);
        jRadioButtonPapelesSi.setText("Si");

        buttonGroupPapeles.add(jRadioButtonPapelesNo);
        jRadioButtonPapelesNo.setText("No");

        jButtonAgregar.setText("Agregar");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });

        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        jLabelID.setText("ID:");

        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        jLabelLlantas.setText("Llantas:");

        jComboBoxLlantas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        jComboBoxLlantas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxLlantasActionPerformed(evt);
            }
        });

        jButtonBuscar.setText("Buscar");

        jLabelFoto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelFotoStr.setText("Foto:");

        jLabelSeguro.setText("Tiene Seguro?");

        buttonGroupSeguro.add(jRadioButtonSeguroSi);
        jRadioButtonSeguroSi.setText("Si");

        buttonGroupSeguro.add(jRadioButtonSeguroNo);
        jRadioButtonSeguroNo.setText("No");

        jLabelLujo.setText("Nivel de Lujo:");

        jComboBoxLujo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100" }));
        jComboBoxLujo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxLujoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelAnio)
                            .addComponent(jLabelID)
                            .addComponent(jLabelFotoStr))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldAnio)
                            .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldFoto)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelPapeles)
                                    .addComponent(jLabelSeguro))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButtonSeguroSi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRadioButtonSeguroNo))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButtonPapelesSi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRadioButtonPapelesNo))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelPuertas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxPuertas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jLabelLlantas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxLlantas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelLujo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxLujo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelModelo)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldModelo)))
                .addGap(18, 18, 18)
                .addComponent(jLabelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonVolver)
                            .addComponent(jButtonEliminar)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jButtonAgregar))
                            .addComponent(jButtonModificar, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addComponent(jButtonBuscar, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelID)
                            .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelModelo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAnio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelFotoStr))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEliminar)
                    .addComponent(jLabelPapeles)
                    .addComponent(jRadioButtonPapelesSi)
                    .addComponent(jRadioButtonPapelesNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSeguro)
                    .addComponent(jRadioButtonSeguroSi)
                    .addComponent(jRadioButtonSeguroNo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelLujo)
                        .addComponent(jComboBoxLujo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonVolver)
                        .addComponent(jLabelPuertas)
                        .addComponent(jComboBoxPuertas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelLlantas)
                        .addComponent(jComboBoxLlantas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jComboBoxPuertasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPuertasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPuertasActionPerformed

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        // TODO add your handling code here:
        try {
            if ( jTextFieldID.getText().isEmpty() ) { error("Error, por favor ingresar un id para el auto."); limpiar(false,0); }
            else if ( !isNumeric(jTextFieldID.getText()) ) { error("Error, por favor ingresar un id numerico."); limpiar(false,0); }
            else if ( jTextFieldID.getText().length() > 5 ) { error("Error, por favor ingresar un id menor o igual a 5."); limpiar(false,0); }
            else if ( jTextFieldModelo.getText().isEmpty() ) { error("Error, por favor ingresar el modelo."); limpiar(false,1); }
            else if ( jTextFieldModelo.getText().length() > 15 ) { error("Error, por favor ingresar un modelo entre 1 y 15 caracteres."); limpiar(false,1); }
            else if ( jTextFieldModelo.getText().length() > 15 ) { error("Error, por favor ingresar un modelo entre 1 y 15 caracteres."); limpiar(false,1); }
            else if ( jTextFieldAnio.getText().isEmpty() ) { error("Error, por favor ingresar el año del auto." ); limpiar(false,2); }
            else if ( jTextFieldAnio.getText().length() < 1 || jTextFieldAnio.getText().length() > 50 ) { error("Error, por favor ingresar unaño entre 1 y 50 caracteres." ); limpiar(false,2); }
            else if ( jTextFieldFoto.getText().isEmpty() ) { error("Error, por favor ingresar el nombre de la foto."); limpiar(false,3); }
            else if ( jTextFieldFoto.getText().length() > 15 ) { error("Error, por favor ingresar el nombre de la imagen entre 1 y 15 caracteres."); limpiar(false,3); }
            else {
                int id = Integer.parseInt(jTextFieldID.getText()), lujo = Integer.parseInt(jComboBoxLujo.getSelectedItem().toString());
                String modelo = jTextFieldModelo.getText(), anio = jTextFieldAnio.getText(), foto = jTextFieldFoto.getText();
                byte papeles = ( jRadioButtonPapelesSi.isEnabled() ) ? (byte)1:(byte)0, seguro = ( jRadioButtonSeguroSi.isEnabled() ) ? (byte)1:(byte)0, puertas = Byte.parseByte(jComboBoxPuertas.getSelectedItem().toString()), llantas = Byte.parseByte(jComboBoxLlantas.getSelectedItem().toString());
                Auto auto = new Auto(id, modelo, anio, foto, papeles,
                                     puertas, llantas, lujo, seguro);
                Datos.agregar(auto);
                valido("Los datos del Auto, fueron guardados.");
                limpiar(true,0);
            }
        } catch (Exception e) {
            error("Error, Uno de los datos ingresados no es valido."); 
            limpiar(false,0);
        }
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        // TODO add your handling code here:
        int n = JOptionPane.showConfirmDialog(null,
                                            "Esta seguro que desea volver atras?",
                                            "Mensaje",
                                            0);
        if (n == JOptionPane.YES_OPTION ) { this.setVisible(false); }
        
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        // TODO add your handling code here:
        try{
            if ( jTextFieldID.getText().isEmpty() ) { error("Error, por favor ingresar un id para el auto."); limpiar(false,0); }
            else if ( !isNumeric(jTextFieldID.getText()) ) { error("Error, por favor ingresar un id numerico."); limpiar(false,0); }
            else if ( jTextFieldID.getText().length() > 5 ) { error("Error, por favor ingresar un id menor o igual a 5."); limpiar(false,0); }
            else if ( jTextFieldModelo.getText().isEmpty() ) { error("Error, por favor ingresar el modelo."); limpiar(false,1); }
            else if ( jTextFieldModelo.getText().length() > 15 ) { error("Error, por favor ingresar un modelo entre 1 y 15 caracteres."); limpiar(false,1); }
            else if ( jTextFieldModelo.getText().length() > 15 ) { error("Error, por favor ingresar un modelo entre 1 y 15 caracteres."); limpiar(false,1); }
            else if ( jTextFieldAnio.getText().isEmpty() ) { error("Error, por favor ingresar el año del auto." ); limpiar(false,2); }
            else if ( jTextFieldAnio.getText().length() < 1 || jTextFieldAnio.getText().length() > 50 ) { error("Error, por favor ingresar un año entre 1 y 50 caracteres." ); limpiar(false,2); }
            else if ( jTextFieldFoto.getText().isEmpty() ) { error("Error, por favor ingresar el nombre de la foto."); limpiar(false,3); }
            else if ( jTextFieldFoto.getText().length() > 15 ) { error("Error, por favor ingresar el nombre de la imagen entre 1 y 15 caracteres."); limpiar(false,3); }
            else {
                int id = Integer.parseInt(jTextFieldID.getText()), lujo = Integer.parseInt(jComboBoxLujo.getSelectedItem().toString());
                String modelo = jTextFieldModelo.getText(), anio = jTextFieldAnio.getText(), foto = jTextFieldFoto.getText();
                byte papeles = ( jRadioButtonPapelesSi.isEnabled() ) ? (byte)1:(byte)0, seguro = ( jRadioButtonSeguroSi.isEnabled() ) ? (byte)1:(byte)0, puertas = Byte.parseByte(jComboBoxPuertas.getSelectedItem().toString()), llantas = Byte.parseByte(jComboBoxLlantas.getSelectedItem().toString());
                Auto auto = new Auto(id, modelo, anio, foto, papeles,
                                     puertas, llantas, lujo, seguro);
                Datos.modificar(auto);
                valido("Los datos del Auto, fueron modificados.");
                limpiar(true,0);
            }
        } catch (Exception e) {
            error("Error, Uno de los datos ingresados no es valido."); 
            limpiar(false,0);
        }
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        // TODO add your handling code here:
        if ( jTextFieldID.getText().isEmpty() ) { error("Error, por favor ingresar el numero de auto."); limpiar(false,0); }
        else if ( !isNumeric( jTextFieldID.getText() ) ) { error("Error, por favor ingresar el numero del auto en números." ); limpiar(false,0); }
        else {
            int n = JOptionPane.showConfirmDialog(null, "¿Desea eliminar este Auto?", "Mensaje de confirmación", 0);
            if(n==JOptionPane.YES_OPTION){
                if ( Datos.eliminar( Integer.parseInt(jTextFieldID.getText()) ) ) { limpiar(true,0); valido("Los datos del auto fueron eliminados."); }
                else error("Error, el número de id no corresponde a ningun auto registrado.");
            }
        }
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jComboBoxLlantasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxLlantasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxLlantasActionPerformed

    private void jComboBoxLujoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxLujoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxLujoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupPapeles;
    private javax.swing.ButtonGroup buttonGroupSeguro;
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JComboBox<String> jComboBoxLlantas;
    private javax.swing.JComboBox<String> jComboBoxLujo;
    private javax.swing.JComboBox<String> jComboBoxPuertas;
    private javax.swing.JLabel jLabelAnio;
    private javax.swing.JLabel jLabelFoto;
    private javax.swing.JLabel jLabelFotoStr;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelLlantas;
    private javax.swing.JLabel jLabelLujo;
    private javax.swing.JLabel jLabelModelo;
    private javax.swing.JLabel jLabelPapeles;
    private javax.swing.JLabel jLabelPuertas;
    private javax.swing.JLabel jLabelSeguro;
    private javax.swing.JRadioButton jRadioButtonPapelesNo;
    private javax.swing.JRadioButton jRadioButtonPapelesSi;
    private javax.swing.JRadioButton jRadioButtonSeguroNo;
    private javax.swing.JRadioButton jRadioButtonSeguroSi;
    private javax.swing.JTextField jTextFieldAnio;
    private javax.swing.JTextField jTextFieldFoto;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldModelo;
    // End of variables declaration//GEN-END:variables
}
