/***  Objetivo:  El objetivo de este Jframe almacena la interfaz grafica para calcular todos los valores
 * de procedimiento,remedios,chequeo; ademas de entregar el total de la cuenta.
 ***@version    V1.0 2/11/2016
 *@author    Ariel Troncoso/Enzo Troncoso
 */
package view;
import model.Auto;
import auto.Datos;
import auto.RegistroConsultas;
import javax.swing.JOptionPane;
import java.text.DecimalFormat;
/**
 *
 * @author AriieelEsteban
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }
    
    private void limpiar( boolean valor, int i ){
        if ( valor ) {
            jTextFieldIva.setText("");
            jTextFieldIvaLujo.setText("");
            jTextFieldID.setText("");
            jTextFieldProcedimientos.setText("");
            jTextFieldSeguro.setText("");
        }
        switch(i){
            case 0: { jTextFieldID.requestFocus(); } break;
            case 1: { jTextFieldIva.requestFocus(); } break;
            case 2: { jTextFieldProcedimientos.requestFocus(); } break;
            case 3: { jTextFieldSeguro.requestFocus(); } break;
            default: {
                jTextFieldID.requestFocus();
            }
            break;
        }
    }
    public static boolean isNumeric(String str)  
    {  
        try { double d = Double.parseDouble(str); }  
        catch(NumberFormatException nfe) { return false; }
        return true;  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNroID = new javax.swing.JLabel();
        jLabelTotalCuenta = new javax.swing.JLabel();
        jLabelDescuento = new javax.swing.JLabel();
        jLabelTotalFinal = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jTextFieldTotalInicial = new javax.swing.JTextField();
        jTextFieldIvaLujo = new javax.swing.JTextField();
        jTextFieldTotalFinal = new javax.swing.JTextField();
        jButtonCalcular = new javax.swing.JButton();
        jLabelIVA = new javax.swing.JLabel();
        jLabelSeguro = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jTextFieldIva = new javax.swing.JTextField();
        jTextFieldSeguro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuRegistro = new javax.swing.JMenu();
        jMenuItemRegistrar = new javax.swing.JMenuItem();
        jMenuItemListado = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenu();
        jMenuItemSi = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consulta");

        jLabelNroID.setText("Nro ID:");

        jLabelTotalCuenta.setText("Total Inicial:");

        jLabelDescuento.setText("IVA Por Lujo:");

        jLabelTotalFinal.setText("Total Final:");

        jTextFieldTotalInicial.setEditable(false);

        jTextFieldIvaLujo.setEditable(false);

        jTextFieldTotalFinal.setEditable(false);

        jButtonCalcular.setText("Calcular Precio");
        jButtonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularActionPerformed(evt);
            }
        });

        jLabelIVA.setText("IVA:");

        jLabelSeguro.setText("Seguro:");

        jTextFieldIva.setEditable(false);

        jTextFieldSeguro.setEditable(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Valores Finales");

        jLabel3.setText("Copyright © 2016 - Ariel / Enzo");

        jMenuRegistro.setText("Autos");
        jMenuRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRegistroActionPerformed(evt);
            }
        });

        jMenuItemRegistrar.setText("Registrar");
        jMenuItemRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistrarActionPerformed(evt);
            }
        });
        jMenuRegistro.add(jMenuItemRegistrar);

        jMenuItemListado.setText("Listado");
        jMenuItemListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListadoActionPerformed(evt);
            }
        });
        jMenuRegistro.add(jMenuItemListado);

        jMenuBar1.add(jMenuRegistro);

        jMenuSalir.setText("Salir");
        jMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalirActionPerformed(evt);
            }
        });

        jMenuItemSi.setText("Si");
        jMenuItemSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSiActionPerformed(evt);
            }
        });
        jMenuSalir.add(jMenuItemSi);

        jMenuBar1.add(jMenuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addComponent(jSeparator3)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(jLabelNroID)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addComponent(jButtonCalcular))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelIVA)
                                    .addComponent(jLabelSeguro)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelTotalCuenta)
                                        .addComponent(jLabelDescuento, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabelTotalFinal, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldTotalInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldIvaLujo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldTotalFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextFieldSeguro, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldIva, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel4))))
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNroID)
                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCalcular))
                .addGap(2, 2, 2)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldTotalInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTotalCuenta))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelIVA, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSeguro))
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldIvaLujo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelDescuento))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTotalFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTotalFinal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void error( String text ) {
        JOptionPane.showMessageDialog(null,
                 text,
                 "Revisar los Datos", JOptionPane.ERROR_MESSAGE);
    }
    public void valido( String text ) {
        JOptionPane.showMessageDialog(null,
                 text,
                 "Mensaje", JOptionPane.PLAIN_MESSAGE);
    }
    
    private void jMenuRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRegistroActionPerformed

    }//GEN-LAST:event_jMenuRegistroActionPerformed

    private void jButtonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularActionPerformed
        // TODO add your handling code here:
        try{
            if ( jTextFieldID.getText().isEmpty() ) { error("Error, ingresar un número de ficha."); limpiar(false,0); }
            else if ( jTextFieldID.getText().length() > 5 ) { error("Error, por favor ingresar un número de ficha menor o igual a 5."); limpiar(false,0); }
            else if ( jTextFieldIva.getText().trim().isEmpty() ) { error("Error, ingresar el precio del chequeo."); limpiar(false,1); }
            else if ( !isNumeric(jTextFieldIva.getText()) ) { error("Error, el precio del chequeo debe ser numerico."); limpiar(false,1); }
            else if ( Integer.parseInt(jTextFieldIva.getText().trim()) > 2000000000 ) { error("Error, ingresar el precio del chequeo menor a 2 millones."); limpiar(false,1); }
            else if ( jTextFieldProcedimientos.getText().isEmpty() ) { error("Error, ingresar el precio de los procedimientos."); limpiar(false,2); }
            else if ( !isNumeric(jTextFieldProcedimientos.getText()) ) { error("Error, el precio del procedimiento debe ser numerico."); limpiar(false,2); }
            else if ( Integer.parseInt(jTextFieldProcedimientos.getText()) > 2000000000 ) { error("Error, ingresar un precio para los procedimientos menor a 2 millones."); limpiar(false,2); }
            else if ( jTextFieldSeguro.getText().isEmpty() ) { error("Error, ingresar el precio de los remedios."); limpiar(false,3); }
            else if ( !isNumeric(jTextFieldSeguro.getText()) ) { error("Error, el precio de los remedios deben ser numericos."); limpiar(false,1); }
            else if ( Integer.parseInt(jTextFieldSeguro.getText()) > 2000000000 ) { error("Error, ingresar el precio de los remedios menor a 2 millones."); limpiar(false,3); }
            else {
                Auto auto = Datos.buscar( jTextFieldID.getText() );
                RegistroConsultas consulta = new RegistroConsultas(
                                            auto, 
                                            Integer.parseInt(jTextFieldIva.getText().trim()),
                                            Integer.parseInt(jTextFieldSeguro.getText()), 
                                            Integer.parseInt(jTextFieldProcedimientos.getText()));
                consulta.obtenerTotalCuenta();
                consulta.descontar();
                consulta.obtenerTotalFinal();
                
                DecimalFormat formato = new DecimalFormat("###,###");
                String descuento = formato.format(consulta.getDescuento()), totalCuenta = formato.format(consulta.getTotalCuenta()), totalFinal = formato.format(consulta.getTotalFinal());
                jTextFieldIvaLujo.setText("$"+descuento);
                jTextFieldTotalInicial.setText("$"+totalCuenta);
                jTextFieldTotalFinal.setText("$"+totalFinal);
            }
        } catch (Exception e) {
            error("Error, Uno de los datos ingresados no es valido."); 
            limpiar(false,0);
        }
    }//GEN-LAST:event_jButtonCalcularActionPerformed
  
    private void jMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalirActionPerformed
    }//GEN-LAST:event_jMenuSalirActionPerformed

    private void jMenuItemSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSiActionPerformed
        // TODO add your handling code here:
        int n = JOptionPane.showConfirmDialog(null,
                                            "Esta seguro que desea salir?",
                                            "Mensaje",
                                            0);
        if (n == JOptionPane.YES_OPTION ) { System.exit(0); }
    }//GEN-LAST:event_jMenuItemSiActionPerformed

    private void jMenuItemRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistrarActionPerformed
        // TODO add your handling code here:
        new Registro().setVisible(true);
    }//GEN-LAST:event_jMenuItemRegistrarActionPerformed

    private void jMenuItemListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListadoActionPerformed
        // TODO add your handling code here:
        if ( Datos.obtenerAuto().isEmpty() ) error("Error, no hay mascotas guardadas.");
        else {
            String texto="";
            for(Auto xx: Datos.obtenerAuto())
            {
                texto += xx.toString()+"\n";
            }
            JOptionPane.showMessageDialog(null,""+texto,
                    "Listado de Pacientes", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItemListadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalcular;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelDescuento;
    private javax.swing.JLabel jLabelIVA;
    private javax.swing.JLabel jLabelNroID;
    private javax.swing.JLabel jLabelSeguro;
    private javax.swing.JLabel jLabelTotalCuenta;
    private javax.swing.JLabel jLabelTotalFinal;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemListado;
    private javax.swing.JMenuItem jMenuItemRegistrar;
    private javax.swing.JMenuItem jMenuItemSi;
    private javax.swing.JMenu jMenuRegistro;
    private javax.swing.JMenu jMenuSalir;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldIva;
    private javax.swing.JTextField jTextFieldIvaLujo;
    private javax.swing.JTextField jTextFieldSeguro;
    private javax.swing.JTextField jTextFieldTotalFinal;
    private javax.swing.JTextField jTextFieldTotalInicial;
    // End of variables declaration//GEN-END:variables
}
